---
Name: silverware-font-icons
---

# Configure Admin Requirements:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - silverware-font-icons/admin/client/dist/styles/bundle.css
  extra_requirements_javascript:
    - silverware-font-icons/admin/client/dist/js/bundle.js
